@startuml

actor Абонент1
actor Абонент2
participant "Сервер" as Server

Абонент1 -> Server: подключиться()
Server -> Абонент1: подтвердить подключение

Абонент1 -> Server: отправитьСообщение(Абонент2, сообщение)
Server -> Абонент2: доставитьСообщение(сообщение)
Абонент2 -> Server: подтвердитьПолучение()

Абонент2 -> Абонент1: ответитьНаСообщение()
Абонент1 -> Server: получитьСообщение()

Абонент1 -> Server: отключиться()
Server -> Абонент1: подтвердить отключение

@enduml