name: example-actions
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Setup python environment
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest